package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/bulga138/panka/toml" // Usando tu paquete TOML
)

// Config holds all user-configurable settings for the editor.
type Config struct {
	TabSize          int
	ShowLineNumbers  bool
	ShowNonPrintable bool // <-- ADD THIS
	EnableLogger     bool
}

// DefaultConfig returns the default editor settings.
func DefaultConfig() Config {
	return Config{
		TabSize:          4,
		ShowLineNumbers:  true,
		ShowNonPrintable: false, // Default off
		EnableLogger:     false,
	}
}

// getConfigPath returns the full path to the config file.
// Uses os.UserConfigDir() for cross-platform compatibility.
func getConfigPath() (string, error) {
	configDir, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("could not find config directory: %w", err)
	}

	// Create a "panka" subdirectory
	pankaConfigDir := filepath.Join(configDir, "panka")

	// Create the directory if it doesn't exist
	if err := os.MkdirAll(pankaConfigDir, 0755); err != nil {
		return "", fmt.Errorf("could not create config directory: %w", err)
	}

	// Return the full path to the config file
	return filepath.Join(pankaConfigDir, "config.toml"), nil
}

// LoadConfig tries to load the config from the user's config directory.
func LoadConfig() Config {
	cfg := DefaultConfig()
	configPath, err := getConfigPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Warning: %v. Using default config.\n", err)
		return cfg
	}

	f, err := os.ReadFile(configPath)
	if err != nil {
		return cfg // No config file, use defaults
	}

	// Usar tu parser TOML
	data, err := toml.ParseNative(string(f))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", configPath, err)
		return cfg // Error parsing, use defaults
	}

	// Mapear manualmente del mapa a la estructura
	if tabSize, ok := data["tabSize"].(int64); ok { // TOML parsea números como int64
		cfg.TabSize = int(tabSize)
	}

	if showLineNumbers, ok := data["showLineNumbers"].(bool); ok {
		cfg.ShowLineNumbers = showLineNumbers
	}

	if showNonPrintable, ok := data["showNonPrintable"].(bool); ok {
		cfg.ShowNonPrintable = showNonPrintable
	}

	if enableLogger, ok := data["enableLogger"].(bool); ok {
		cfg.EnableLogger = enableLogger
	}

	// Asegurar que los valores sean lógicos
	if cfg.TabSize <= 0 {
		cfg.TabSize = DefaultConfig().TabSize
	}

	return cfg
}

func SaveConfig(cfg Config) error {
	configPath, err := getConfigPath()
	if err != nil {
		return err
	}

	// Manually format the TOML content.
	content := fmt.Sprintf(
		`# panka editor configuration
# This file was generated by panka. You can edit it manually.

# Number of spaces for a tab.
tabSize = %d

# Whether to show line numbers on startup (toggled with Ctrl+L).
showLineNumbers = %t

# Whether to show non-printable characters like spaces, tabs, and newlines (toggled with Ctrl+O).
showNonPrintable = %t

# Set to true to enable debug logging to 'panka.log'.
enableLogger = %t
`, cfg.TabSize, cfg.ShowLineNumbers, cfg.ShowNonPrintable, cfg.EnableLogger)

	// Write the file
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Printf("Default config file created at: %s\n", configPath)
	return nil
}
